# Generated by Django 5.2.14 on 2026-05-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_update_site"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="genre",
            field=models.CharField(
                choices=[
                    ("SF", "SF"),
                    ("アクション", "アクション"),
                    ("コメディ", "コメディ"),
                    ("サスペンス", "サスペンス"),
                    ("ドラマ", "ドラマ"),
                    ("ファンタジー", "ファンタジー"),
                    ("ホラー", "ホラー"),
                    ("ミステリー", "ミステリー"),
                    ("恋愛", "恋愛"),
                    ("その他", "その他"),
                ],
                max_length=80,
            ),
        ),
    ]
