# Generated by Django 5.2.14 on 2026-06-01 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_alter_movie_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="sub_genre",
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
